# Generated by Django 2.0.1 on 2018-02-06 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0002_auto_20180206_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpson',
            name='date_create',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='gpsub',
            name='date_create',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
