# Generated by Django 2.0.1 on 2018-02-12 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0003_auto_20180206_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Espregister',
            fields=[
                ('id_esp', models.AutoField(primary_key=True, serialize=False)),
                ('mac', models.CharField(blank=True, max_length=255, null=True)),
                ('date_create', models.DateTimeField(default=datetime.date.today)),
            ],
        ),
    ]
