# Generated by Django 2.0.1 on 2018-02-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0004_espregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='espregister',
            name='cmp_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
